# The intention with the "rollup" groups is that we were getting several PRs opened every day for one dependency each;
# since we require branches to be up to date before merging this causes a fair amount of thrash every day:
# 1. Open 4 PRs
# 2. Their CI builds race, first gets merged
# 3. The other 3 then must update and re-run
# 4. Repeat steps 2 and 3 until all are merged; when there's 4 PRs that means ~10 CI runs
#
# This causes even more problems when humans are trying to get PRs merged at the same time.

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      rollup:
        patterns:
          - "*"
    ignore:
      - dependency-name: "zip"
        # We want to avoid upgrading zip > 3.X as it causes dependency conflicts when used in one of FOSSA's
        # private code-bases.
        # TODO: Validate that this is still necessary after June 2026
        # See https://teamfossa.slack.com/archives/C039KE5ERNE/p1750981935221269
        versions: [ ">=4.0.0" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      rollup:
        patterns:
          - "*"
