# The intention with the "rollup" groups is that we were getting several PRs opened every day for one dependency each;
# since we require branches to be up to date before merging this causes a fair amount of thrash every day:
# 1. Open 4 PRs
# 2. Their CI builds race, first gets merged
# 3. The other 3 then must update and re-run
# 4. Repeat steps 2 and 3 until all are merged; when there's 4 PRs that means ~10 CI runs
#
# This causes even more problems when humans are trying to get PRs merged at the same time.

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      rollup:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      rollup:
        patterns:
          - "*"
