name: dynamic
on: pull_request

jobs:
  check-build:
    strategy:
      matrix:
        settings:
        - host: windows-latest
          setup: echo "no setup"
          build: cargo build --release
          test: cargo nextest run --release
        - host: ubuntu-latest
          setup: echo "no setup"
          build: cargo build --release
          test: cargo nextest run --release --features ci
        - host: macos-latest
          setup: |
            rustup target add aarch64-apple-darwin &&
            rustup target add x86_64-apple-darwin
          build: |
            cargo build --release --target aarch64-apple-darwin &&
            cargo build --release --target x86_64-apple-darwin
          test: |
            cargo nextest run --target aarch64-apple-darwin --release &&
            cargo nextest run --target x86_64-apple-darwin --release

    runs-on: ${{ matrix.settings.host }}
    name: test / ${{ matrix.settings.host }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: dtolnay/rust-toolchain@stable
    - uses: taiki-e/install-action@nextest
    - uses: Swatinem/rust-cache@v2.8.0
      with:
        key: ${{ matrix.settings.host }}
    - run: ${{ matrix.settings.setup }}
    - run: ${{ matrix.settings.build }}
    - run: ${{ matrix.settings.test }}
    - run: cargo check --all --bins --examples --tests
    - run: cargo test --doc
